package.path = package.path .. os.getenv("HOME") .. ".config/nvim/lua"
-- 立即生效
-- vim.cmd("autocmd BufWritePost $MYVIMRC source $MYVIMRC"
require "sjjwantfish.keymaps"
require "sjjwantfish.options"
require "sjjwantfish.plugins"
require "sjjwantfish.colorscheme"
require "sjjwantfish.cmp"
require "sjjwantfish.lsp"
require "sjjwantfish.telescope"
require "sjjwantfish.treesitter"
require "sjjwantfish.autopairs"
require "sjjwantfish.gitsigns"
require "sjjwantfish.nvim-tree"
require "sjjwantfish.bufferline"
require "sjjwantfish.toggleterm"
require "sjjwantfish.indentLine"

