-- 立即生效
-- vim.cmd("autocmd BufWritePost $MYVIMRC source $MYVIMRC"

-- require("user.diverdown")

require("user.keymaps")
require("user.options")
require("user.plugins")
require("user.colorscheme")
require("user.lualine")
require("user.cmp")
require("user.tabnine")
require("user.marks")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.gitsigns")
require("user.nvim-tree")
require("user.bufferline")
require("user.toggleterm")
require("user.indentLine")
require("user.trouble")
require("user.comment")
require("user.lsp_dap")
-- require("user.transparent")
