-- vim.cmd [[
-- try
--   colorscheme neon
-- catch /^Vim\%((\a\+)\)\=:E185/
--   colorscheme default
--   set background=dark
-- endtry
-- ]]
--
-- require('github-theme').setup()
-- require("tokyonight").setup({
--     transparent = true,
--       styles = {
--         sidebars = "transparent",
--         floats = "transparent",
--       },
-- })
vim.cmd[[colorscheme tokyonight]]
